# Generated by Django 5.0.6 on 2026-05-20 12:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('application_type', models.CharField(choices=[('Recordation', 'Recordation'), ('Renewal', 'Renewal'), ('Change of Ownership', 'Change of Ownership'), ('Change of Name', 'Change of Name'), ('Discontinuation', 'Discontinuation')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('NEED_MORE_INFO', 'Need More Info'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_comment', models.TextField(blank=True, null=True)),
                ('reviewer_decision', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEED_MORE_INFO', 'Need More Info')], max_length=20, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('NEED_MORE_INFO', 'Need More Info'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='applications.application')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['tracking_number'], name='application_trackin_19940e_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_1508e0_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='application_created_c6d08d_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant_email'], name='application_applica_02cc48_idx'),
        ),
    ]
